YourQuestionnaire/urls.py
from .settings import STATIC_URL, STATIC_ROOT
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('questionnaire.urls')),
] + static(STATIC_URL, document_root=STATIC_ROOT)

questionnaire/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='questionnaireIndex'),
    path('create_poll/', create_poll, name='create_poll'),
    path('create_question/<int:quiz_id>', create_question, name='create_question'),
    path('create_answer/', create_answer, name='create_answer'),
    path('my_polls/', QuizListView.as_view(), name='my_poll'),
    path('go_poll/', go_poll, name='go_poll'),
    path('take_poll/<int:poll_id>', take_poll, name='take_poll'),
    path('rating/<int:poll_id>', rating, name='rating'),
]

questionnaire/models.py
from django.contrib.auth.models import User
from django.db import models


class Quiz(models.Model):
    title = models.CharField(max_length=64, verbose_name='Название')
    description = models.CharField(max_length=256, verbose_name='Описание')
    topic = models.CharField(max_length=64, verbose_name='Тема')
    lifetime = models.DateTimeField(verbose_name='Действует до')
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')

    def __str__(self):
        return f'{self.title}, {self.topic}'

    class Meta:
        verbose_name = 'Опрос'
        verbose_name_plural = 'Опросы'


class Question(models.Model):
    question = models.CharField(max_length=64, verbose_name='Вопрос')
    quiz = models.ForeignKey('Quiz', on_delete=models.CASCADE, verbose_name='Опрос', related_name='questions')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')

    def __str__(self):
        return f'{self.question}'

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'


class AnswerQuestion(models.Model):
    answer = models.CharField(max_length=64, verbose_name='Ответ')
    question = models.ForeignKey('Question', on_delete=models.CASCADE, verbose_name='Вопрос', related_name='answers')
    correct = models.BooleanField(default=False, verbose_name='Это правильный ответ?')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')

    def __str__(self):
        return f'{self.answer}'

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'


class UserAnswer(models.Model):
    quiz = models.ForeignKey('Quiz', on_delete=models.CASCADE, verbose_name='Опрос', related_name='user_quiz', null=True)
    question = models.ForeignKey('Question', on_delete=models.CASCADE, verbose_name='Вопрос',
                                 related_name='user_question', null=True)
    answers = models.ForeignKey('AnswerQuestion', on_delete=models.CASCADE, verbose_name='Ответ',
                                 related_name='user_answer', null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')


class PassedPolls(models.Model):
    quiz = models.ForeignKey('Quiz', on_delete=models.CASCADE, verbose_name='Опрос', related_name='passed_quiz')
    passed_user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Закончил опрос')


class Rating(models.Model):
    answer_number = models.IntegerField(verbose_name='Число звёзд')
    comment = models.CharField(max_length=750, blank=True, default='Комментарий не добавлен!')
    quiz = models.ForeignKey('Quiz', on_delete=models.CASCADE, verbose_name='Опрос', related_name='rating')
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

questionnaire/forms.py
from django.forms import ModelForm, DateTimeInput, Select
from django.http import QueryDict

from .models import *


class DateTimeInput(DateTimeInput):
    input_type = 'datetime-local'


class QuizForm(ModelForm):
    class Meta:
        model = Quiz
        fields = ('title', 'description', 'topic', 'lifetime',)
        widgets = {
            'lifetime': DateTimeInput(),
        }


class QuestionForm(ModelForm):
    def __init__(self, quiz, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['quiz'].empty_label = "Не выбрано!"

        if quiz is not None:
            if isinstance(quiz, QueryDict):
                qs = Quiz.objects.filter(pk=quiz['quiz']).all()
            else:
                qs = Quiz.objects.filter(pk=quiz[0].pk).all()
            self.initial['quiz'] = qs[0].pk
            self.fields['quiz'].queryset = qs

    class Meta:
        model = Question
        fields = ('question', 'quiz',)
        widgets = {
            'quiz': Select(attrs={'class': 'form-control'}),
        }


class AnswerForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['question'].empty_label = "Не выбрано!"
        self.fields['question'].queryset = self.fields['question'].queryset.order_by('-pk')

    class Meta:
        model = AnswerQuestion
        fields = ('answer', 'question', 'correct',)
        widgets = {
            'question': Select(attrs={'class': 'form-control', 'placeholder': 'Не выбрано!'}),
        }

questionnaire/views.py
from lib2to3.fixes.fix_input import context
from typing import Union

from django.contrib import messages
from django.forms import ModelForm
from django.http import HttpResponseNotFound, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.views.generic import ListView

from .forms import QuizForm, QuestionForm, AnswerForm
from .models import Quiz, UserAnswer, Question, PassedPolls, AnswerQuestion, Rating


class QuizListView(ListView):
    model = Quiz
    template_name = 'questionnaire/my_poll.html'
    context_object_name = 'my_polls'
    paginate_by = 16

    def get_queryset(self):
        if self.request.user.is_authenticated:
            my_polls = Quiz.objects.filter(user=self.request.user).order_by('-created_at').prefetch_related()
            return my_polls

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['UserAnswer'] = UserAnswer
        context['PassedPolls'] = PassedPolls

        return context

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.method.lower() in self.http_method_names:
                handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed
            return handler(request, *args, **kwargs)
        else:
            return redirect("account_login")


def index(request):
    return render(request, 'questionnaire/index.html')


@login_required
def create_poll(request):
    if request.method == 'GET':
        context = {
            'form': QuizForm()
        }
        return render(request, 'questionnaire/create_poll.html', context)
    form = QuizForm(request.POST)
    if form.is_valid():
        form_with_user = form.save(commit=False)
        form_with_user.user = request.user
        form_with_user.save()
        messages.success(request, 'Вы успешно создали опрос!')
        return redirect('create_question', form_with_user.pk)
    messages.error(request, 'Хм, что-то не то!')
    return redirect('create_poll')


@login_required
def create_question(request, quiz_id):
    quiz = Quiz.objects.filter(pk=quiz_id).all()
    if request.method == 'GET':
        context = {
            'form': QuestionForm(quiz),
        }
        return render(request, 'questionnaire/create_question.html', context)
    form = QuestionForm(None, request.POST)
    return process_form(request, form, quiz_id)


@login_required
def create_answer(request):
    if request.method == 'GET':
        context = {
            'form': AnswerForm()
        }
        return render(request, 'questionnaire/create_answer.html', context)
    form = AnswerForm(request.POST)
    return process_form(request, form, message_success='Вы создали ответ на вопрос!', func_redirect='create_answer')


@login_required
def my_poll(request):
    my_polls = Quiz.objects.filter(user=request.user).order_by('-created_at').prefetch_related()
    context = {
        'my_polls': my_polls,
        'UserAnswer': UserAnswer,
        'PassedPolls': PassedPolls,
    }
    return render(request, 'questionnaire/my_poll.html', context)


@login_required
def go_poll(request):
    if request.method == 'GET':
        return render(request, 'questionnaire/go_poll.html')
    if not request.POST.get('poll_id') or not request.POST.get('poll_id').isdigit():
        messages.error(request, 'Значение поля id опроса не корректно!')
        return render(request, 'questionnaire/go_poll.html')
    return redirect('take_poll', request.POST.get('poll_id'))


@login_required
def take_poll(request, poll_id):
    try:
        poll = Quiz.objects.get(pk=poll_id)
    except Quiz.DoesNotExist:
        messages.error(request, 'Вы указали не верный id опроса!')
        return redirect('go_poll')
    question = check_possibility_passing_poll(request, poll)
    if isinstance(question, HttpResponseNotFound):
        return question
    if request.method == 'GET':
        return get_standart_render(request, poll, question)
    number_question = request.POST.get('number_question')
    answers = request.POST.get('answers')

    all_question = poll.questions.all()
    # Обрабатываем кнопку "Назад", если нажата, возвращаем предыдущий вопрос
    if request.POST.get('redirect') and number_question:
        question = all_question.filter(pk=int(number_question)).first()
        return get_standart_render(request, poll, question)

    if not (number_question and answers):
        messages.error(request, 'Вы передали не все параметры!')
        return get_standart_render(request, poll, question)

    for i in request.POST.lists():
        answers = i[1] if i[0] == 'answers' else []  # Получаем ответ, который дал пользователь
    try:
        UserAnswer.objects.get(quiz=poll, question=get_object_or_404(Question, pk=int(number_question)),
                               user=request.user).delete()
    except:
        pass
    answer = UserAnswer(quiz=poll, question=get_object_or_404(Question, pk=int(number_question)),
                        answers=AnswerQuestion.objects.filter(pk=int(answers[0]))[0], user=request.user)
    answer.save()

    number_iter = 1
    while True:
        question = all_question.filter(pk=int(number_question) + number_iter).first()

        # Проверяем, есть ли вопрос, если нет, то сообщаем об успешном прохождении опроса
        if not question:
            passed_quiz = PassedPolls(quiz=poll, passed_user=request.user)
            passed_quiz.save()
            messages.info(request, 'Вы успешно прошли опрос!')
            return redirect('rating', poll_id)
        if not question.answers.all():
            number_iter += 1
            continue
        break
    return get_standart_render(request, poll, question)


def rating(request, poll_id: int):
    quiz = Quiz.objects.get(pk=poll_id)
    if request.method == 'POST':
        try:
            rating_quiz = Rating.objects.get(user=request.user, quiz=quiz)
            rating_quiz.delete()
        except:
            pass
        rating_quiz = Rating(answer_number=request.POST.get('rating'), comment=request.POST.get('comment'),
                             quiz=quiz, user=request.user)
        rating_quiz.save()
        messages.success(request, 'Вы успешно оставили отзыв!')
        return redirect('questionnaireIndex')
    context = {
        'poll': quiz
    }
    return render(request, 'questionnaire/rating.html', context)


def check_possibility_passing_poll(request, poll: Quiz) -> Union[Question, HttpResponseNotFound]:
    """
    Используется для проверки возможности пройти определённый опрос пользователем.
    request: WSGIRequest
    return: Question (вопрос на который пользователь будет отвечать)
            or HttpResponseNotFound (сообщение о невозможности пройти опрос).
    """
    check_poll_lifetime = _check_poll_lifetime(poll)
    if not isinstance(check_poll_lifetime, bool):
        return check_poll_lifetime
    if PassedPolls.objects.filter(quiz=poll, passed_user=request.user):
        return HttpResponseNotFound("Вы уже прошли этот опрос!")
    for question in poll.questions.all():
        if len(question.answers.all()) > 0:
            return question
    return HttpResponseNotFound("В этом опросе нет вопросов с ответами")


def get_standart_render(request, poll: Quiz, question: Question) -> HttpResponse:
    """ Возвращает стандартную страницу для ответа на вопрос в опросе. """
    context = {
        'poll': poll,
        'question': question,
    }
    return render(request, 'questionnaire/take_poll.html', context)


def process_form(request, form: ModelForm, id: Union[None, int] = None, message_success: str = 'Вы создали вопрос!',
                 message_error: str = 'Хм, что-то не то!',
                 func_redirect: str = 'create_question', ) -> HttpResponseRedirect:
    if form.is_valid():
        form.save()
        messages.info(request, message_success)
        if not id:
            return redirect(func_redirect)
        return redirect(func_redirect, id)
    messages.error(request, message_error)
    if not id:
        return redirect(func_redirect)
    return redirect(func_redirect, id)


def _check_poll_lifetime(poll: Quiz) -> Union[bool, HttpResponseNotFound]:
    """ Проверяем не кончился ли срок жизни опроса. """
    date_now = timezone.now()
    date_now.astimezone(timezone.utc).replace(tzinfo=None)
    if poll.lifetime <= date_now:
        return HttpResponseNotFound("Срок действия опроса истёк!")
    return True

questionnaire/templates/questionnaire/create_answer.html
{% extends 'questionnaire/template/base.html' %}
{% load static %}
{% block header %}
    <title>Добавить вопрос - YourQuestionnaire</title>
    {% include "questionnaire/includes/header.html" %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}
{% block content %}

    <form class="decor" method="post" action="{% url 'create_answer' %}">
        <div class="form-left-decoration"></div>
        <div class="form-right-decoration"></div>
        <div class="circle"></div>
        <div class="form-inner">
            <h3>Добавить ответ</h3>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Добавить">
            <center><a href="{% url 'questionnaireIndex' %}"><small>Завершить добавление ответов</small></a></center>
        </div>
    </form>

    </div>
{% endblock %}

questionnaire/templates/questionnaire/create_poll.html
{% extends 'questionnaire/template/base.html' %}
{% load static %}
{#{% block header %}{% endblock %}#}
{% block content %}
    <title>Создать опрос - YourQuestionnaire</title>
    <link rel="stylesheet" href="{% static 'css/form.css' %}">

    <form class="decor" method="post" action="{% url 'create_poll' %}">
        <div class="form-left-decoration"></div>
        <div class="form-right-decoration"></div>
        <div class="circle"></div>
        <div class="form-inner">
            <h3>Создать опрос</h3>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Создать">
        </div>
    </form>

    </div>
{% endblock %}

questionnaire/templates/questionnaire/create_question.html
{% extends 'questionnaire/template/base.html' %}
{% load static %}
{% block content %}
    <style>
    label[for='id_quiz']{
        display: none;
    }
    #id_quiz{
        display: none;
    }
    </style>
    <title>Добавить вопрос - YourQuestionnaire</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/form.css' %}">

    <form class="decor" method="post">
        <div class="form-left-decoration"></div>
        <div class="form-right-decoration"></div>
        <div class="circle"></div>
        <div class="form-inner">
            <h3>Добавить вопрос</h3>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Добавить">
            <center><a href="{% url 'create_answer' %}"><small>Завершить добавление вопросов</small></a></center>
        </div>
    </form>

    </div>
{% endblock %}

questionnaire/templates/questionnaire/go_poll.html
{% extends 'questionnaire/template/base.html' %}
{% load static %}
{% block content %}
    <title>Пройти опрос - YourQuestionnaire</title>
    <link rel="stylesheet" href="{% static 'css/form.css' %}">

    <form class="decor" method="post" action="{% url 'go_poll' %}">
        <div class="form-left-decoration"></div>
        <div class="form-right-decoration"></div>
        <div class="circle"></div>
        <div class="form-inner">
            <h3>Пройти опрос</h3>
            {% csrf_token %}
            <br>
            <label>Введите id опроса:</label>
                <input oninput="this.value = this.value.replace(/[^0-9]/g, '');" type="text" placeholder="Введите id опроса" name="poll_id" required>
            <input type="submit" value="Перейти">
        </div>
    </form>

    </div>
{% endblock %}

questionnaire/templates/questionnaire/index.html
{% extends 'questionnaire/template/base.html' %}
{% block content %}
    <!DOCTYPE html>
    <html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              crossorigin="anonymous">
        <title>Главная страница - YourQuestionnaire</title>
    </head>
    <body>

    <style>
        input[type="submit"] {
            width: 33%;
        }
    </style>

    <div class="container text-center">
        <div class="row content">
            <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1"></div>
            <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 nomargin">
                <br>
                <br>
                <br>
                <br>
                <h1 class="p-2 text-center">Твой Опросник</h1>
                <br>
                <br>
                <center><img
                        src="https://www.univ-silkroad.uz/media/k2/items/cache/69b5f85da08d181d48515c6d41e3e0a5_L.jpg"
                        alt="Фото опросник" width="500"></center>
                <br>
                <h2>Как создать опрос</h2>
                Составить интересную анкету, заполнить которую будет не в тягость, а в радость, довольно просто. Но
                нужно
                знать несколько основных правил:
                <ol><br>
                    <li>Определитесь с целью анкеты. Сфокусируйтесь на одной конкретной цели. Так вы сможете собрать
                        релевантную
                        информацию и не запутать пользователя.
                    </li>
                    <br>
                    <li>Поймите, какую информацию собирать. Как только станет понятна цель, выберете, какие именно
                        данные и
                        в
                        каком формате собирать.
                    </li>
                    <br>
                    <li>Будьте объективны. Убедитесь, что задаёте только прямые вопросы, избегая наводящих конструкций.
                        Некоторые
                        слова — такие, как «запретить» могут повлиять на результат вопроса.
                        К примеру, вопрос «Мы получаем множество положительных отзывов от наших счастливых клиентов. Как
                        вы
                        считаете, на сколько хорош наш сервис?» — пример того, как вопрос подталкивает отвечающего быть
                        более
                        благосклонным к вашей компании. Попробуйте попросить «Оцените удобство нашего сервиса по
                        5-балльной
                        шкале»
                        и
                        предложите эту шкалу.
                        И ещё. Не позволяйте себе строить догадки и включать их в вопросы.
                    </li>
                    <br>
                    <li>Следите за порядком вопросов. Логичная последовательность вопросов важна, как для вас, так и для
                        проходящего опрос. Самый оптимальный вариант — «от общего к частному».
                    </li>
                    <br>
                    <li>Избегайте двойных вопросов. Один блок — один вопрос. Иначе вы получите искажённую информацию.
                    </li>
                    <br>
                    <li>Пишите простым языком. В опросниках не стоит использовать жаргон и сложные обороты. Сделайте
                        свою
                        анкету
                        простой и понятной и тогда каждый респондент наверняка дойдёт до финального вопроса.
                    </li>
                    <br>
                    <li>Протестируйте опросник. Пришлите готовую анкету друзьям и коллегам, чтобы ещё раз проверить
                        логику
                        опроса
                        и разглядеть возможные ошибки.
                    </li>
                    <br>
                </ol>
                {% if user.is_authenticated %}
                    <form action="{% url 'create_poll' %}">
                        <center><input class="btn btn-primary p-2" type="submit" value="Создать опрос"></center>
                    </form>
                {% else %}
                    <center>Для создания опроса вам необходимо <a href="{% url 'account_login' %}">авторизоваться</a>
                    </center>
                {% endif %}
                <br><br>
            </div>
        </div>
    </div>
    </body>
    </html>

{% endblock %}

questionnaire/templates/questionnaire/my_poll.html
{% extends 'questionnaire/template/base.html' %}
{% load static %}
{% load questionnaire_tags %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/dynamic_background.css' %}">
    <link rel="stylesheet" href="{% static 'css/list_poll.css' %}">
{% endblock %}

{% block content %}

    <div class="row" id="row" style="width: 100%;">
        <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1"></div>
        <div class="col-xs-10 col-sm-12 col-md-10 col-lg-10">
            <ol class="bullet">

                <center><h1>Мои опросы</h1></center>
                <br>

                {% for poll in my_polls %}

                    <li>
                        <span>{{ poll.title }}</span>
                        <br>
                        <span><small>{{ poll.description }}</small></span>
                        <hr>
                        <p><label class="pointer" id="{{ forloop.counter }}"
                                  onclick="showQuestion(this, 'quest-'+this.id, 2)"><strong><i>Нажмите
                            для
                            отображения вопросов и ответов</i></strong></label></p>
                        <div id="quest-{{ forloop.counter }}" style="display: none;">
                            {% for question in poll.questions.all %}

                                <p>Вопрос: <strong>{{ question.question }}</strong></p>
                                <label title="{{ question.question }}">Варианты ответов:</label>
                                {% for answer in question.answers.all %}
                                    {% if answer.correct %}
                                        <p title="Это правильный ответ">{{ forloop.counter }}) {{ answer.answer }} ✅</p>
                                    {% else %}
                                        <p title="Это не правильный ответ">{{ forloop.counter }}) {{ answer.answer }}
                                            ❌</p>
                                    {% endif %}
                                {% endfor %}
                                <br>
                                <hr>

                            {% endfor %}
                            <label style="float: right"><small>Можно пройти до: {{ poll.lifetime }}</small></label>
                            <br>
                        </div>
                        <br>
                        <p><label class="pointer" id="press_show_statistic"
                                  onclick="showQuestion(this, 'poll-info-{{ forloop.counter }}', 1)"><strong><i>Нажмите
                            для отображения статистики опроса</i></strong></label></p>
                        <div id="poll-info-{{ forloop.counter }}" style="display: none;">
                            Прошли опрос: {{ poll.passed_quiz.all|length }}
                            {% if poll.passed_quiz.all|length > 0 %}
                                <div class="row">
                                    {% for passed_quiz in poll.passed_quiz.all %}
                                        <hr>
                                        <label style="margin-top: 35px;"><strong><big>Имя: {{ passed_quiz.passed_user }}</big></strong></label>
                                        {% for passed_question in passed_quiz.quiz.user_quiz.all %}
                                            {% if passed_question.user == passed_quiz.passed_user %}
                                                <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4"
                                                     style="margin-top: 20px;">
                                                    <label>Вопрос: {{ passed_question.question }}</label><br>

                                                    <label style="{% if passed_question.answers.correct %}background-color: LimeGreen;{% else %}background-color: Salmon;{% endif %}">Ответ
                                                        пользователя: {{ passed_question.answers }}</label><br>
                                                    <label>
                                                        <small>Правильный ответ(ы):
                                                            {% for answer in passed_question.question.answers.all %}
                                                                {% if answer.correct %}
                                                                    <span><strong>{{ answer }} </strong></span><br>
                                                                {% endif %}
                                                            {% endfor %}
                                                        </small>
                                                    </label>
                                                </div>
                                                <br>
                                            {% endif %}
                                        {% endfor %}

                                    {% endfor %}
                                </div>
                                <hr>
                                <p>{{ poll|statistic:user.pk|safe }}</p>
                            {% endif %}
                        </div>
                        <br>
                        <label style="float: right"><small>Создан: {{ poll.created_at }}</small></label>
                        <p onclick="copyURL('copy_url-{{ poll.pk }}')">
                            <input type="hidden" value="http://{{ request.get_host }}{% url 'take_poll' poll.pk %}"
                                   id="copy_url-{{ poll.pk }}">
                            <small>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-subtract" viewBox="0 0 16 16">
                                    <path d="M0 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v2h2a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-2H2a2 2 0 0 1-2-2V2zm2-1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H2z"/>
                                </svg>
                                <label class="pointer">Скопировать ссылку</label>
                            </small>
                        </p>

                    </li>

                {% endfor %}

            </ol>
        </div>
    </div>

    {% include 'questionnaire/includes/pagination.html' %}

    <script>
        function showQuestion(element, id, statusSend) {
            el = document.getElementById(id)
            console.log(el, id, statusSend)
            text = {
                1: '<strong>Нажмите для отображения статистики опроса</strong>',
                2: '<strong>Нажмите для отображения вопросов и ответов</strong>',
                3: 'Нажмите для скрытия статистики опроса',
                4: 'Нажмите для скрытия вопросов и ответов',
            }
            if (el.style.display === 'none') {
                el.style = 'display: block;'
                element.textContent = text[statusSend + 2]
            } else {
                el.style = 'display: none;'
                element.innerHTML = text[statusSend]
            }
        }

        function copyURL(id) {
            const str = document.getElementById(id).value;
            const el = document.createElement('textarea');
            el.value = str;
            el.setAttribute('readonly', '');
            el.style.position = 'absolute';
            el.style.left = '-9999px';
            document.body.appendChild(el);
            el.select();
            document.execCommand('copy');
            document.body.removeChild(el);

            const ul = document.getElementById('messages-list')
            const li = document.createElement('li')
            const div = document.createElement('div')
            div.textContent = 'Ссылка успешно скопирована!'
            div.classList = 'alert alert-info msg fade show'
            div.role = 'alert'
            li.appendChild(div)
            ul.appendChild(li)
            fade_alerts()
        }
    </script>

{% endblock %}